### PR TITLE
I am unable to understand the question

### PR DESCRIPTION
**Pull request by somyatyagiji**
i am unable to understand the question

### CODE REVIEW

**Comment by rishikeshsamant** [comment]
Where you got stuck?

**Comment by somyatyagiji** [comment]
After write 6-7 line of code 
At every point

**Comment by rishikeshsamant** [comment]
If you see the question after declaring array,  you have to initialize it by providing values mentioned in data, use loops for that.

**Comment by somyatyagiji** [comment]
- My mind get blank after reading the question

**Comment by rishikeshsamant** [comment]
No worry, its part of development. Try to break question into parts and understand them one by one. Implement it and if you are stuck even then try to use chatgpt/google to ask related doubt.

**Review by rishikeshsamant — APPROVED** [review]

**Pull request merged**
