### PR TITLE
some done some not

### PR DESCRIPTION
**Pull request by somyatyagiji**
i don't understand the complete question

### CODE REVIEW

**Review by rishikeshsamant — CHANGES_REQUESTED** [review]
Day 18 has only problema and you have to code in a single file.

**Comment by somyatyagiji** [comment]
sorry I just forget to delete the second file

**Review by rishikeshsamant — CHANGES_REQUESTED** [review]
Their are many small to big syntax and semanatics error. Try to fix them, one by one after reading terminal.

**Comment by somyatyagiji** [comment]
Ya I know there are many error not only in the syntax also  I don't write the complete code because whatever I understand from the question I write and left those one where I am unable to understand

**Review by rishikeshsamant — APPROVED** [review]

**Pull request merged**
